name = "personal-runway-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "http://localhost:5173"

[[kv_namespaces]]
binding = "RUNWAY_CACHE"
id = "da7be3dfd1a248b193cb60925881c8ad"
preview_id = "1df2b1e6cec74208bd74eb89c334934f"

[triggers]
crons = ["17 */6 * * *"]
